/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author LG
 */
public class Menu extends javax.swing.JPanel {
    
    private ArrayList<JLabel> opcao;

    /**
     * CLASSE QUE EXIBE UM MENU RETANGULAR VERTICAL COM 20 LINHAS PARA EXIBIÇÃO
     * DE INFORMAÇÕES.
     */
    public Menu(int x , int y) {
        initComponents();
        this.setBounds( x , y ,140, 440);
        this.setBackground(Color.blue);
        this.setVisible(true);
        
        opcao = new ArrayList<JLabel>();
        
        for ( int i = 0 ; i < 21 ; i++ ){
            JLabel nova = new JLabel("empty"+1);
            nova.setVisible(true);
            nova.setForeground(Color.white);
            nova.setBounds(10, 5 + (20*i) , 120, 20);
            opcao.add(nova);
            this.add(nova);
        }
        
        
    }
    /**
     * RECEBE UM ARRAY DE STRING QUE DEFINIRÁ O TEXTO DE CADA LINHA
     * @param opt 
     */
    public void setMenuOptions(ArrayList<String> opt){
        int i = 0;
        for ( String optt : opt){
            opcao.get(i).setText(optt);
            i++;
        }
        while( i < opcao.size()){
            opcao.get(i).setText("");
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
